Product:
  type: object
  properties:
    productId:
      type: integer
      format: int64
    productName:
      type: string
    availableSizes:
      type: array
      items:
        type: string
    availableColors:
      type: array
      items:
        type: string
    fabric:
      type: string
    shortDesc:
      type: string
    longDesc:
      type: string
    basePrice:
      type: number
      format: float
    sellPrice:
      type: number
      format: float
    discPrice:
      type: number
      format: float
    discPercent:
      type: number
      format: float
    avgRating:
      type: number
      format: float
