Product:
  type: object
  properties:
    productName:
      type: string
    fabric:
      type: string
    basePrice:
      type: number
    sellPrice:
      type: number
    discPrice:
      type: number
    discPercent:
      type: integer
      format: int64
