# ADD/CREATE Product API
add_product:
  post:
    summary: Add a product to the store
    operationId: createProduct
    requestBody:
      description: Create a new Product
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
    responses:
      '201':
        description: Created product
      '400':
        description: Product already exists

# GET Products List API
products_list:
  get:
    summary: Get a list of products
    operationId: fetchAllProducts
    responses:
      '200':
        description: Products List data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiResponse"

# GET Product Details API
get_product_details:
  get:
    summary: Get Product details by Product ID
    operationId: fetchProductById
    parameters:
      - in: path
        name: productId
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
          description: The identifier of the Product.
    responses:
      "200":
        description: A single Product with the given Id.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiResponse"
