# ADD/CREATE Product API
add_product:
  post:
    summary: Add a product to the store
    operationId: createProduct
    requestBody:
      description: Create a new Product
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
    responses:
      '201':
        description: Created product
      '400':
        description: Product already exists

# GET Products List API
product_list:
  get:
    summary: Get a list of products
    responses:
      '200':
        description: Audit scores data
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Product'

